/* 
VAMOS A CREAR UN PROGRAMA QUE ME PERMITA CALCULAR LOS AÑOS EN LOS CUALES HUBO MUNDIAL DE LA FIFA, DESDE SU INICIO HASTA UN AÑO LIMITE DEFINIDO ARBITRARIAMENTE POR EL USUARIO 
(RECORDEMOS QUE LOS MUNDIALES SE CELEBRAN CADA CUATRO AÑOS Y EL PRIMER MUNDIAL FUE EN 1930) 

NOTAS:
- EL OBJETIVO DE TENER UNA FECHA LIMITE ES PARA EVITAR QUE EL PROGRAMA SE CONVIERTA EN UN BUCLE INFINITO DE PROCESAMIENTO INCAPAZ DE SALIR DE LA CONDICION QUE DEFINIMOS, SI ESTO OCURRE 
ES MUY PROBABLE QUE VSCODE TERMINE CRASHEANDO O INCLUSO QUE SE CONGELE EL PC
 */

const firstWFC = 1930;
const limitYear = parseInt(prompt(`Hasta que año desea calcular la fecha de los mundiales?`));


//Usando While
// let i = firstWFC;
// while (i <= limitYear) {
//     console.log(`${i}`);
//     i += 4;
// } 


//Usando For
for (let i = firstWFC; i <= limitYear; i += 4) {
    console.log(`${i}`);
}